[package]
name = "filup_http"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0"
actix-multipart = "0"
actix-web = "4"
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0"
lazy_static = "1"
log = "0"
serde = { version = "1", features = ["derive"] }
tera = "1"
